version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "7070:7070" # Expose the frontend port to Nginx

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "7071:7071" # Expose the backend port to Nginx
    environment:
      - NODE_ENV=production